### ISSUE TITLE
Library not working properly and outdated with SoftWire

### ISSUE THREAD

**Issue by BaltasarParreira** [stevemarple/MLX90614#3]
Hi, first the class SoftWire no longer has set, I mean setSclHigh, setSclLow and so on.
They changed to only the signal name without the "set", like for example sclHigh, sclLow...

Second the examples don't compile because of the previous problem but also and mainly on the MLX90614_read_config.ino because the syntax of mlx90614.read that in the example uses MLX90614::read(uint8_t&) when in the library is defined as MLX90614::read(uint8_t, uint16_t&).

The first I manage to change for the right new set sintax, but for the MLX90614::read I'm still trying to understand how can be used the declared " uint8_t command, uint16_t &value "

**Comment by stevemarple** [comment]
This should be fixed in v0.1.5.
